---
- hosts: test
  remote_user: root
#  sudo: yes
  vars:
    hostname: "{{ansible_hostname}}"
  tasks:
    - name: cp zabbix-release_2.2-1+wheezy_all.deb
      copy: src=zabbix-release_2.2-1+wheezy_all.deb dest=/opt/zabbix-release_2.2-1+wheezy_all.deb

    - name: install zabbix repo
      apt: deb="/opt/zabbix-release_2.2-1+wheezy_all.deb" state=present
    - name: apt-get update
      apt: update_cache=yes


    - name: install zabbix agent 2.2
      apt: name=zabbix-agent state=present

    - name: Copy zabbix configuration to /etc/zabbix/zabbix_agentd.conf
      template: src=zabbix_agentd.j2 dest=/etc/zabbix/zabbix_agentd.conf
      notify: restart zabbix

    - name: ensure zabbix running on power
      service: name=zabbix-agent enabled=yes
  handlers:

    - name: restart zabbix
      service: name=zabbix-agent state=restarted
