---
- hosts: all

  tasks:
  - name: install zabbix repo
    yum: name="http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm" state=present
  - name: install zabbix agent
    yum: name=zabbix-agent state=present
  - name: copy zabbix conf
    copy: src=files/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  - name: start zabbix service
    service: name=zabbix-agent enabled=yes state=restarted
