---
- hosts: test
  remote_user: aca
  sudo: yes
  vars:
    hostname: "{{ansible_hostname}}"
    server_name: "zabbix.hq.eastmoney.com"
    # server_name: "192.168.100.28"
  tasks:
  - iptables:
      chain: INPUT
      source: 8.8.8.8
      protocol: tcp
      destination_port: 10050
      jump: ACCEPT
    become: yes

